#!/usr/bin/env bash

#    ----------------------------------------------------------------------
#    Copyright © 2025  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

_global_variables() {
  chroot_path=""
  quiet=""
}

_msg_info() {
  local \
    _msg=() \
    _line
  _msg=(
    "$@"
  )
  if [[ "${quiet}" == "n" ]]; then
    for _line \
      in "${_msg[@]}"; do
      _printf \
        '[%s] INFO: %s\n' \
        "${app_name}" \
        "${_line}"
    done
  fi
}

_graphical_environment_setup() {
  local \
    _chroot="${1}" \
    _paths=() \
    _mountpoint \
    _path \
    _msg=()
  _paths+=(
    '/run/dbus'
    '/run/udev'
  )
  for _path in "${_paths[@]}"; do
    _mountpoint="${_chroot}${_path}"
    _mounted="$(
      mount |
        awk \
          '{print $3}' |
        grep \
          "${_mountpoint}")"
    if [[ "${_mounted}" == "" ]]; then
      mount \
        -o \
          bind \
        "${_path}" \
        "${_mountpoint}"
    else
      _msg=(
        "Path '${_path}' already"
        "mounted on '${_mountpoint}'."
      )
      _msg_info \
        "${_msg[*]}"
    fi
  done
}

_set_overrides() {
  if [[ "${quiet}" == "" ]]; then
    quiet="n"
  fi
}

_usage() {
  local \
    _exit="${1}" \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Extra mounts (udev and dbus) for running a graphical environment from a chroot.

Usage:
  ${app_name}
    [options]
    <chroot-path>

  options:
     -h                     This message.
     -v                     Enable verbose output
ENDUSAGETEXT
  printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${_exit}"
}

getopts_opts="$(
  printf \
    "%s" \
    "vh")"
while \
  getopts \
    "${getopts_opts}" \
    arg; do
  case \
    "${arg}" in
    v)
      quiet="n" ;;
    h)
      _set_overrides
      _usage \
        0 ;;
    *)
      if [[ " ${getopts_opts} " != *"${arg}"* ]]; then
        _msg=(
          "Invalid argument '${arg}'."
        )
        _msg_error \
          "${_msg[*]}" \
          0
        _usage \
          1
      fi ;;
  esac
done
shift $((
  OPTIND - 1 ))
if (( "${#}" < 1 )); then
  _msg=(
    "Setting '/mnt' as"
    "argument."
  )
  _msg_info \
    "${_msg[*]}"
  chroot_path="/mnt"
elif (( 0 < "${#}" )); then
  chroot_path="${1}"
fi
_set_overrides
app_opts=(
  "${chroot_path}"
)

_graphical_environment_setup \
  "${app_opts[@]}"
